[features]
seeds = false
skip-lint = false

[programs.localnet]
simple_store = "5dGGmRfwYqKg3WXhcmG7ioxeLmw8pQMUYNxbvbibaJ5z"
vault_chain = "HSQMtGMTM4LfmQt7qGB52ZhpCH8LVAVYJcV2Q3ZDqfzJ"

[programs.devnet]
simple_store = "5dGGmRfwYqKg3WXhcmG7ioxeLmw8pQMUYNxbvbibaJ5z"
vault_chain = "HSQMtGMTM4LfmQt7qGB52ZhpCH8LVAVYJcV2Q3ZDqfzJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha --require ts-node/register --timeout 1000000 tests/**/*.ts"

