[features]
seeds = false
skip-lint = false

[programs.localnet]
vault_chain = "SvmjFVPgVBBwEAV9p1w9CAF8sCmvBPjxPhhgXcNVBTe"

[programs.devnet]
vault_chain = "SvmjFVPgVBBwEAV9p1w9CAF8sCmvBPjxPhhgXcNVBTe"

[registry]
url = "https://api.dev.solflare.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha --require ts-node/register --timeout 1000000 tests/**/*.ts"

